
from app.models import db, Event

# Adds a demo user, you can add other users here if you want
def seed_events():
    Demo1 = Event( ambassador_id=7,title= 'West African Cooking With Chef Phoebe', description="Jollof Rice is a popular West African dish that is full flavor! Although historians believe this dish originated from Senegal, many West African countries claim to have the original and best Jollof rice. In the class you will be learning how to cook the Nigeruan version of the dish. Flavors of the spiced tmoato stew base and the smoky undertones in this rice dish willl have you asking for more. In this class you will be learning how to be making this iconic african dish wirh Chef Phoebe. Chef Phoebe has taken years to perfect her family recipe and will teach you her award winning recipe." ,cost=23 )

    featured = Event( ambassador_id=1,title= 'West African Cooking With Chef Phoebe', description="Jollof Rice is a popular West African dish that is full flavor! Although historians believe this dish originated from Senegal, many West African countries claim to have the original and best Jollof rice. In the class you will be learning how to cook the Nigeruan version of the dish. Flavors of the spiced tmoato stew base and the smoky undertones in this rice dish willl have you asking for more. In this class you will be learning how to be making this iconic african dish wirh Chef Phoebe. Chef Phoebe has taken years to perfect her family recipe and will teach you her award winning recipe." ,cost=23 )

    Demo3=Event( ambassador_id=3,title="Cooking South African Street Food", description="The Gatsby, a south African street food favorite is a delicious signature sandwich consisting of a crusty, toasted roll that is stuffed with bologna slices, French fries, ketchup, lettuce, and hot piri-piri sauce. In this class you will learn how to make this delicious sandwich and learn about the culinary history of south african food",cost=30)
    Demo4=Event( ambassador_id=4,title="Snacking the Moroccan Way", description="Moroccan has a rich and vibrant food culture. In this class you will be learning how to make Harsha, a very popular snack. Harsha is a bread that is a made with a combination of semolina, sugar, butter, milk, and baking powder that is traditionally made in a pan and is noted for its soft crumbly texture, and is raditionally served with butter, honey, or chease. After we learn to make this delicious snack we will discuss morrocan food and the external influences on it.",cost=20)
    Demo5=Event( ambassador_id=5,title="Vegetable Soup the Nigerian Way", description="Take a trip to the western African country of Nigeria! Join us in the kitchen to make Efo-Riro, a hearty Nigerian soup Native to the Yoruba People. This delicious dish consists of stock cubes, pumpkin leaves, onions, tomatoes and fish. The name of this dish in Yoruba is vegetable soup. This dish is traditionally is served fufu, a dough that is made from pounded plaintains. ***Due to the complexity of fufu we will send the fufu premade***",cost=24)
    Demo6=Event( ambassador_id=6,title="Morrocan Dessert Time with Amira", description="Join us to learn how to make one of Morrocos best treats, Fekkas! Fekkas traditional Moroccan twice-baked cookies come in both sweet and savory versions. They are prepared with shortbread or yeasted dough that is usually enriched with orange blossom water, aniseed, or citrus zest, as well as toasted nuts and dried fruit such as almonds, walnuts, raisins, pistachios, or sesame seeds.  ",cost=30)
    Demo7=Event( ambassador_id=7,title="Su-Shee with Chef Su", description="Sushi(すし, 寿司, 鮨)Sushi is Japan's most famous culinary dish, typically made with rice and fillings which have been rolled inside a a sheet of dry seaweed. Surprisingly, the term sushi is an umbrella term covering a wide range of sub-varieties which can be made with a myriad of different ingredients and in as many forms and presentations.Although the dish has become wrongly synonymous with raw fish, the primary ingredient of every type of sushi is only vinegared rice. Originally, sushi was only a method of preserving fish - first developed in Southeast Asia, but it reached Japan in the 8th century.Over time, the dish slowly transformed. Rice was no longer fermented but vinegared and eaten together with fish, and by the 19th century, sushi as we know it today was invented. Besides rice, which can be white or brown, other ingredients include seafood, meat, and vegetables that can be either raw or cooked.Firstly, we will be making the original type of sushi, nigirizushi. This is prepared by draping a mound of rice with a sliced topping, frequently with some wasabi in between or on the side. Lastly, we will be making a type of sushi known worldwide is makizushi. Makizushi is small, usually bite-sized cylindrical pieces most commonly wrapped in nori — a sheet of dry seaweed.Sushi can be eaten with chopsticks or fingers, and it is typically served on a platter or in a bento box with a compartment for dips (usually soy sauce). Due to the worldwide popularity of sushi, many variations of the dish developed outside of Japan.",cost=45)
    Demo8=Event( ambassador_id=8,title="Bangers with Banga soup", description="Taste the soup of the niger delta. Banga or ofe akwu is a flavorful Nigerian soup made with palm fruit, beef or dried fish, vegetables, and seasonings such as salt and chili pepper. The soup is traditionally paired with various fufu dishes. The name of the dish is derived from two words: ofe, meaning soup or stew, and akwu, meaning palm fruit.",cost=23)
    Demo9=Event( ambassador_id=9,title="Rahh- Mehn", description='''Ramen
    (ラーメン, Shina Soba, Chūka Soba, Ramyeon, 라면)

    Ramen is a noodle soup that first appeared in Japan in 1910, when Chinese cooks combined the noodles with a salty broth. These curly noodles were of bright yellow color and more elastic than the Japanese noodles prepared at the time – the dough was kneaded with a sodium carbonate-infused mineral water called kansui.
    In 1958, its name was derived from the pronunciation of the Chinese word lamian (pulled noodles), and that same year, Nissin Foods produced the first-ever instant version of noodles with a chicken-flavored broth called Chickin Ramen.
    Shortly after, the dish started to be exported around the world. Ramen should be cooked al dente and eaten quickly while it is still hot. It is not recommended to leave the noodles sitting in the broth for too long, as they tend to become too soft and mushy.
    The dish can be either kotteri (rich) or assari/paitan (light), depending on the opaqueness and the heaviness of the broth which is usually made using animal bones or dried seafood mixed with onions, garlic, ginger, leeks, and mushrooms.
    Two most famous types of ramen are ramen of Kyushu, prepared with a boiled pork bone broth called tonkotsu, and ramen of Hokkaido, made with a traditional seasoning called red miso.
    In this class we will be making ramen of Kyushu and discussing Chinese influence on some traditional Japanese dishes. ''',cost=30)
    Demo10=Event( ambassador_id=10,title='The Best Mochi with Mo', description='''Mochi
    (Kagami Mochi, Kinako Mochi, Sakuramochi, Kashiwa-Mochi, Hishi Mochi, Kusha Mochi, Mochi Ice-cream, Daifuku, Tauchi, Palitao, Tangyuan, Butter Mochi, Moachi, Mashu, Loh Mai Chi, Kue Moci, Chapssaltteok, もち, 餅)
    Treat your Family and Friends to some of Mo's delicious Mochi from this worldly class !!
    Mochi, the tiny cakes made out of glutinous rice, are an important part of Japanese cuisine and culture. The preparation of mochi starts with a time-consuming process of pounding boiled or steamed rice, usually the glutinous mochigome variety until it forms into a thick and homogenous paste. ( you will be receiving this with the rest of your ingredients) 
    Later it is rolled and shaped into small circular forms. Although its origins might be in China, mochi has been associated with Japan for centuries. It initially appeared during the Yayoi period, when it was only enjoyed by the aristocracy, up until the Heian period, when it became a food that was commonly prepared and served during religious festivities, as people believed it brings fortune and health.
    Mochi can be incorporated in savory dishes, usually soups and snacks, but most commonly it is made into a confectionery item. In its dessert form, mochi is usually dressed up with food coloring, creating a myriad of delightful color combinations. The most common confectionery is referred to as daifuku - round cakes filled with different ingredients such as the traditional red bean paste, strawberries, or ice cream.
    Due to its chewy texture, it is important to be extra careful and attentive while eating mochi and to take tiny bites of this glutinous treat.''',cost=45)
    Demo11=Event( ambassador_id=11,title="Kenyan Cooking", description="Head to east africa to learn the delicious dish of Githeri. Githeri is a Kenyan staple food consisting of beans and maize that are stewed with onions, tomatoes, and sometimes potatoes or meat chunks. The stew is often flavored with cumin, turmeric, or chili powder. ",cost=40)
    Demo12=Event( ambassador_id=12,title="Eating with Ethiopians", description="In this class you will learn how to make the delicious ethiopan soup Shiro. Shiro is an Ethiopian stew made with chickpeas or broad beans as main ingredients, along with garlic, onions, ginger, tomatoes, and chili peppers. The chickpeas give this stew a nice texture and nutty flavor, ",cost=30)
    Demo13=Event( ambassador_id=13,title="Algerian meal time", description="Rechta is a traditional Algerian dish consisting of thin and flat noodles and chicken sauce. The noodles are made with a combination of flour, salt, water, and ghee, while the sauce is made with chicken pieces, onions, garlic, oil, chickpeas, ras el hanout, cinnamon, turnips, potatoes, and zucchini. ",cost=30)
    Demo14=Event( ambassador_id=14,title="sum dim sum and den sum", description='''Dim sum
    (点心, 點心, Diǎnxīn, Dímsām)
    Dim sum is a variety of bite-sized food that is usually served with tea. It can range from savory dumplings, buns, and noodle rolls to sweet puddings and tarts. In this class we will be treating ourselves to some savory dumplings and sweet pudding so, unleash your sweet tooth!
    The term dim sum translates to touch the heart, and according to legend, it was invented many centuries ago by cooks of the Royal Court in order to touch the heart of Chinese emperors (but not to fully satiate their hunger).
    What started as a simple snack is now a key part of Chinese culture. It is also a ritual family dish eaten on most weekend mornings in Hong Kong. Each dish usually consists of a few pieces of dim sum varieties, served in steamer baskets or on small plates, making them great for sharing or trying out new flavors.
    Whether it is steamed dumplings with pork and prawns, spring rolls, stuffed crab claws, rice porridge congee, pork buns, wo tip dumplings with ground meat or rice noodle rolls, a variety of dim sum will satisfy even the most demanding consumers.''',cost=35)
    Demo15=Event(ambassador_id=15,title="Ro-Ur-Tee (ROTI WITH RO)", description='''Roti
    Upgrade your sandwich game with this incredible Roti recipie by Chef Rolland.
    Roti is a flat and unleavened bread made with wholemeal flour. It is traditionally cooked on an iron griddle called tava, an important vessel in the Indian cuisine. In Indian cuisine, roti is as essential as rice. There are several theories regarding its origin.
    One says that it was invented in Persia, when it was made with maida and was much thicker than today's rotis. Another theory says that it traveled to India from East Africa, where unleavened bread was a staple and the production of wheat was abundant.
    The Ayurveda dates it back to India's Vedic period. Regardless of the origin, roti is nowadays popular throughout the world, in countries such as Pakistan, Nepal, Sri Lanka, Maldives, South Africa, and South Asia. Its name stems from the Sanskrit word रोटिका, meaning bread.
    There are many variations of the basic roti, such as chapati, makki di roti, tandoori roti, and roti canai. In this will be making tandoori roti.
    It is commonly used as an accompaniment to various dishes, including curries, and on the Caribbean, it is commonly used as a sandwich wrap and consumed as street food.''',cost=25)
    Demo16=Event( ambassador_id=16,title="Japanese Yakitori ", description='''Yakitori
    (焼き鳥, やきとり, ヤキトリ)
    Yakitori refers to Japanese grilled chicken where pieces of chicken meat are skewered with a particular type of skewer called kushi (which can be made from either steel or bamboo) and are then traditionally grilled over a charcoal fire.- A few  Kushi's  will be provided with the delivery of your ingredients. 
    Depending on the cut of chicken and the method of preparation, there are various types of this dish. An important step in the making of yakitori is the seasoning, either salty or salty-sweet, which can be done during or after grilling. Salty seasoning is just salt that can sometimes be combined with pepper, while salty-sweet seasoning is actually tare sauce made from mirin, soy sauce, sake, and sugar.
    Present-day versions of yakitori first appeared during the Meiji Era in the 19th century, but once chicken became abundantly available in the 1950s, the popularity of skewered chicken skyrocketed and the dish became popular among the masses. In Japan, yakitori can be purchased in specialized yakitori shops called yakitori-ya, but it is also often served in Japanese gastropubs known as izakaya.
    Since skewered chicken is so easy to prepare, plus it's portable, it is also a popular street food sold at yatai, the small Japanese food stalls. The dish is meant to be eaten with hands only, often directly off the skewer, and can be paired with a side of roasted vegetables, while each bite should ideally be washed down with ice-cold beer.''',cost=40)
    Demo17=Event( ambassador_id=17,title="Biryani Delight ", description='''Biryani
    (Buriyani, Breyani, Briani, Biriyani, Biriani, बिरयानी)
    Biryani is a group of classic dishes which date back to the Mughal Empire. The main ingredients of biryani are rice (ideally basmati), spices, a base of meat, eggs, or vegetables, and numerous optional ingredients such as dried fruits, nuts, and yogurt.
    It is believed that Mumtaz Mahal, Emperor Shah Jahan's queen inspired the dish in the 1600s. The word biryani is derived from the Persian word birian, meaning fried or roasted, and the dish made its way from Persia to India via groups of traders and immigrants.
    Over time, the popularity of biryani spread throughout India and other countries, so there is a huge variety of biryanis today, such as sindhi biryani (made with yogurt), Bombay biryani (with lots of spices and kevra), or Lucknowi biryani (made with a special technique of cooking the meat and rice separately, then together until fully cooked).In this class, we will be making Bombay biryani.
    What was once a dish reserved for royalty is today served in almost every Indian restaurant as one of their specialty dishes, seasoned with cardamom, cinnamon, bay leaves, coriander, or mint leaves, giving it a unique flavor and making biryani a top choice for many customers around the world.''',cost=20)
    Demo18=Event( ambassador_id=18,title="Un-Pho-Gettable ", description='''Pho
    (Phở)
    Pho is a Vietnamese noodle soup, Vietnam's national dish, street food, comfort food, and a way of life. It is also one of the most beloved Vietnamese dishes in the western hemisphere due to its complex, unique flavors, and elegant simplicity. Although it is classified as a soup, pho is served as the main course and the two bowls of it never taste the same.
    It is traditionally made with chicken or beef broth, where the bones simmer lazily for at least three hours until the broth is perfect. The addition of herbs and spices accentuates the flavors, and the chewy rice noodles, juicy beef slices, and crunchy sprouts elevate the dish to another level. 
    There are two main types of Pho in Vietnam - one is Pho Bac, made in the northern parts of the country, with a clear, simple, delicate flavor and spices, without the herbs and garnishes found in Pho Nam, which is made in the southern parts of the country, with added spices, bean sprouts, various toppings, fish, and hoisin sauce.
    It is believed that pho derived from the French pot au feu, but regardless of the legend's truthfulness, pho still remains a staple of comfort food - warm, hearty, and delicious.''',cost=30)
    Demo19=Event( ambassador_id=19,title="Won-Ton-More ", description='''Wonton
    (Yúntūn, Húntun, Chao Shou, Bianshi, 餛飩, 雲吞, 馄饨, 云吞)

    Often referred to as the Chinese ravioli, wontons are a variety of thin-skinned dumplings with meat, seafood or vegetable filling enclosed in tender wheat dough wrappers. Many sources suggest that the origins of wontons date back to the Han dynasty era, when they used to be prepared for the Chinese ancestor worship rituals as offerings to the spirits of the deceased.
    As the Han era concluded, circa 220 CE, the northern Chinese farmers who had long grown wheat discovered they could ground this grain into flour and knead it with water. From this practice emerged an entire world of new dishes known as bing, which was a collective name for steamed breads, grilled flatbreads, noodles, and various dumplings.
    These dishes soon became so popular they were sold anywhere from river boat food vendors to the streets, enjoyed both by royalty and the common folk. Over time, wontons have evolved and spread from Northern China throughout the country and beyond.
    Traditionally prepared during the Winter Solstice Festival, they were cooked in chicken broth until almost translucent and enjoyed as a heartwarming soup typically flavored with white pepper, sesame, and oyster oil. Nowadays, wontons are available in numerous varieties.
    In the North, they are most often stuffed with pork or lamb, while the classic Shanghainese filling includes minced pork and bok choy cabbage, flavored with the wild green called shepherd’s purse. Further to the south, people make their wontons with egg wrappers and fill them with a combination of pork and shrimp, while in Cantonese cuisine, wontons are often served as an appetizer, deep-fried and smothered in sweet-and-sour sauce.
    In the neighboring province of Fujian, they are better known as bianshi and are sometimes stuffed with fish paste. The so-called three treasure wontons, also known as Sanxian huntun or wuxi Sanxian wontons are stuffed with pork, dried shrimps, and pickled vegetables, and typically served in a spicy tofu and egg soup.
    Sichuan pork wontons are called chao shou, and they are traditionally served either in qing tang, a clear vegetable broth flavored with cilantro and other leafy greens, or in a spicy hong you chili oil sauce. Hong Kong-style wontons are filled with shrimp and lightly seasoned pork flavored with ginger, yellow chives, soy sauce, and sesame oil.''',cost=15)
    Demo20=Event( ambassador_id=20,title=" Czech Republic ", description='''Europe is so much more than just ancient history, kings and queens, castles and churches. Europe is also home to some of the tastiest and most interesting food in the world –The Czech Republic is probably most famous for its great variety of pilsner beers, but the country also serves up some tasty Czech foods to soak up all that alcohol. One of the must-eat dishes in Prague are palacinky pancakes. These crepe-like desserts are filled with fruit jam and served rolled up. ''',cost=25)
    Demo21=Event( ambassador_id=21,title="Currywurst in Germany", description="In Germany it’s all about the wurst! There are hundreds of varieties of sausage in Germany but one of the most popular fast food versions (imbiss) is currywurst. You can get currywurst either with or without the skin of the sausage (mit darm for with, ohne darm for without), but either way the sausage comes cut up and is served with ketchup and curry powder sprinkled on top. You can choose different levels of spice and it’s best when eaten with pommes (fries) and a cola.",cost=35)
    Demo22=Event( ambassador_id=22,title="English Breakfast ", description="Wake up in England with Chef William's perfect fried eggs, ham, beans, fried tomatoes and black pudding. Besides the good ol’ fry-up, there is a bonus  greasy bacon butty sandwich recipe in store for our participants. Pull out  your tiaras and lets head to London!",cost=20)
    Demo23=Event( ambassador_id=23,title="In Pizza we Crust ", description="There are few countries as well-known for great cuisine as Italy. And while there’s more to Italian food than just pizza and pasta, you’ve still got to try the original. It seems most cities in Italy are competing for the best pizza, but really, you’ve got to try our very own chef Giada De Carluccio Pizza to get the true taste of Italy. Oh, and while you’re in Italy — might as well get your fill of gelato, too- we will be having a limited edition live making gelato class in the summer so, keep your eyes peeled for that !",cost=37)
    Demo24=Event( ambassador_id=24,title="Herring in Netherlands", description='''This is a dish  for only the brave & adventrous ; the fish will be provided, and we will be having a chat about culinary dishes in Netherlands while making the brine for this popular snack!
    Needless to say, raw herring is an acquired taste and this silvery, slimy snack is definitely not for everyone. Nevertheless, it holds a special place in many Dutch people’s hearts and has been a staple dish of the Netherlands since the Middle Ages. This infamous fish can be bought throughout the country and in summer time herring season comes into full swing, with countless low-landers chowing down on this peculiarly Dutch delicacy.
    Historically a large part of the Dutch economy revolved around the fish trade and herring was a vital commodity. This little fish prefers to move in large schools around shallow coastlines making it an easy catch for fishermen. At some point in the Middle Ages the Dutch began to smoke and salt the fish, preserving it in large barrels that could be transported across Europe and eventually the New World. In the 14th century this process was improved with vinegar, and soon after herbs and spices were added to the mix, creating the variety of brine which is still used in the Netherlands today.
    This brine is much sweeter than other European equivalents and gives the fish a distinctive zing. 
    To even out its flavor the Dutch often pair herring with diced raw onions and gherkins, sprinkling these accompaniments over the fish’s scales. While herring can be eaten inside of a bread roll, this method will garner disapproving looks from locals. Indeed, the only true, Dutch way to eat herring is vertically; with certified Netherlanders dangling the fish above their mouths as they take generous bites from this pickled treat.''',cost=15)
    Demo25=Event( ambassador_id=25,title="Goulash in Hungary", description="The invention of goulash began with one of the humblest groups in Hungarian society, the cowherds, according to the distinguished Hungarian ethnologist Eszter Kisbán. Groups of five or six single men, with their dogs and a couple of horses to pull their supply cart, spent months or even a year at a time out on the plains tending tall, slender gray cattle with long upturned horns. They cooked for themselves in large cauldrons slung from a pole supported by posts over an open fire, using simple, nonperishable supplies: millet, lard, bacon, onions, salt, and sometimes black pepper. If one of the cattle died or was slaughtered, the cowherds would feast on a rare dish of fresh meat, a simple stew made by browning the meat in lard and onions, adding water and, if available, black pepper. At some point, they began substituting coarsely ground dried red chilies from home gardens for the pepper. In the villages, some unknown innovator had rediscovered what was already known in the Americas, that chilies could be dried, crushed underfoot, and pounded in a mortar. By the end of the 18th century, travelers were commenting on this rough, spicy peasant dish that left a pleasant warmth in the stomach.It’s usually a thick stew (or sometimes a soup) with meat and vegetables, seasoned with paprika. It’s best served in a bread bowl and with a beer. ",cost=40)
    Demo26=Event( ambassador_id=26,title="Štruklji in Slovenia", description="Slovenia might not first come to mind as a culinary destination, but the country’s unique placement in central Europe means Slovenian cuisine has taken the best of its neighbouring countries’ cuisines. Located between the Mediterranean, the Alps and ancient Roman sites, you’ll find amazing prosciutto, fine cheeses and hearty meat dishes in Slovenia.But it’s not all savory, the sweets are good too. And the best of the best is a crepe-like dish called Štruklji. These cottage cheese pancakes are made with tarragon (usually reserved for savory dishes) and they’re unique to Ljubljana (the capital)",cost=30)
    Demo27=Event( ambassador_id=27,title="Crème Catalan in Catalonia", description="In accordance with tradition, crème brulee may be very French, but the best custard dish (with burnt caramel) comes from Spain’s northern state of Catalonia. The two countries dispute which came first, but Crème Catalan is cooked on the stove rather than the oven. Just about any trendy restaurant in Barcelona will serve the dish.According to Confectionery Guild of Barcelona, the origins of crema catalana were created by the Jewish inhabitants of Catalonia. As lovers of sweets, they are said to have develop this custard using a combination of milk and eggs. This classic grouping was perfumed by its Moorish influence of cinnamon and lemon, and therefore, has its own specificity of ingredients and flavor to finish. Eating crema catalana quickly spread beyond its Catalonia roots to the rest of Spain, and was designated to be served on March 19th, St. Joseph’s Day (Spanish equivalent of Father’s Day).",cost=45)
    Demo28=Event( ambassador_id=28,title="Carne de sol", description="Spend a night in Brazil with this staple dish!A staple of Northeastern Brazil, carne de sol (lit. meat of the sun) - sometimes also called carne de sereno or simply jabá - refers to heavily salted, sun-dried meat. Carne de sol is traditionally prepared with either beef or goat meat, and the origins of this centuries-old meat preservation method are attributed to the so-called sertanejos, cattle ranchers living in the vast, semi-arid Brazilian hinterlands.Today, carne de sol is a delicacy found all across the country and, if not grilled or cubed and used in various stews, it is typically served with coalho cheese and accompanied by a thick manioc gruel called pirão or boiled cassava.",cost=28)
    Demo29=Event( ambassador_id=29,title="chocolate with coco", description="Pastel de choclo(Pastel de maiz, Corn Pie)Chile's favorite home-cooked meal and Peru's national dish, the soft and creamy pastel de choclo is a casserole-like pie that is also popular in Argentina and Bolivia. It consists of ground beef, black olives, onions, hard-boiled eggs, and corn flour dough called choclo.Corn plays a key role in the dish, and unsurprisingly so – it was worshipped by the ancient Incas whose most important god was the Corn God. Corn was so important to Incas that their chief, believed to be a descendant of the gods, planted the first corn seeds every year.According to anthropologists, the dish probably originates from the Spanish conquerors who hired tribal cooks to make them a meal as a reminder of home. The cooks implemented corn dough into a dish similar to empanadas, and pastel de choclo was born.Nowadays, large raisins are sometimes incorporated into the pie, while the pie itself gets sprinkled with sugar before baking, ensuring that a caramelized crust develops on top. All that's left is to enjoy it while it's hot and consume a delicious slice of culinary history.",cost=30)
    # Demo30=Event( ambassador_id=30,title="Alfajor with Joe", description='''Alfajor
    # (Alfaxor, Alaxur, Alfajores)
    # Alfajor is a type of treat with dulce de leche or milk jam stuffing sandwiched between two sweet cookies. The combination is then coated with a layer of chocolate or sprinkled with confectioners' sugar. The name alfajor stems from the Arabic word al-hasú, which means stuffed or filled.
    # Although the cookies can be found throughout Latin America, they are originally from Andalusia, Spain, invented during the time when the country was occupied by the Moors. When the Spaniards came to America, they brought their foods and traditions along the way, and with time, almost every country in Latin America has adapted the Spanish alfajor to make it their own, so there are a lot of varieties of the basic, original cookie - including fillings such as chocolate mousse, fruit, and cream.
    # In Spain, the cookies are most commonly sold and consumed during the Christmas season, but it should be noted that the traditional Spanish alfajor is quite different from the South American version, consisting of flour, honey, cinnamon, and almonds.''',cost=25)
    # Demo31=Event( ambassador_id=31,title="Ceviche Delight", description='''Ceviche
    # (Cebiche, Seviche, Sebiche)
    # Ceviche is the national dish of Peru consisting of slices of raw fish or shellfish that is spiced with salt, onions, and chili peppers, then marinated in lime juice. Due to the acidity of lime juice, the texture of the fish changes, as does its color – from pink to white.
    # The acidic marinade, also known as leche de tigre (lit. tiger's milk) "cooks" the meat without any heat involved in the process. For ceviche, fresh fish is an imperative, as fish and shellfish that are not fresh can cause food poisoning. Peruvians are used to fresh ingredients, so the fish will sometimes be prepared for ceviche less than an hour after being caught.
    # Fish for ceviche can be divided into three categories: firm, medium, and soft. The dish was originally made by the natives who marinated fish and amarillo chiles in the juices of a native fruit called tumbo, which was replaced by lime juice when the Spanish brought limes and onions to the country.
    # The flavors of ceviche are slightly acidic and spicy, with an intense aroma of the sea. Traditionally, it is served on a bed of lettuce with tiny pieces of corn, chunks of sweet potato, and boiled yuca. Cancha, a variety of popcorn made from large corn kernels toasted in salt and oil provides an ideal side dish.
    # The dish is traditionally served at cevicherias, specialized ceviche restaurants that can be found all over the country, and it is so popular that it even has its day, known as National Ceviche Day.''',cost=30)
    # Demo32=Event( ambassador_id=32,title="Casados Delight", description='''Casados
    # (Comida Tipica)Casados, also known as comida tipica (lit. typical dish), is the most popular dish in Costa Rica. Whichever traditional restaurant (called sodas) you visit, it will most likely be on their menu. Casado consists of white rice, beans, meat such as chicken, beef, or fish, and a salad such as iceberg or coleslaw.
    # Additional side dishes may include avocado slices, French fries, cheese tortillas, fried plantains, and potato-based stews. The name casados translates to married, and it is clearly visible on the plate as all of the ingredients provide a nice balance of protein and carbohydrates, making it a nutritionally valuable dish as well as a tasty one.
    # According to a popular legend, the dish was usually eaten by newlyweds, and as the two would not know the other one's preferences in food, a variety of ingredients would be served on one plate in order to find out the favorites of each newlywed. With a variety of flavors, a clash of aromas, and vibrant, bold colors on the plate, there is surely something for everyone in this tasty dish.''',cost=30)
    # Demo33=Event( ambassador_id=33,title="Baleada", description='''Baleada
    # Baleada is one of the most famous Honduran dishes consisting of a thick wheat flour tortilla filled with mashed fried beans and optionally, various other ingredients such as cheese, eggs, avocados, hot sauce, and Honduran-style sour cream known as mantequilla.
    # It is believed that baleada originated in La Ceiba, on the northern coast. There are two theories about the origin of the name baleada: one says that it is named after the visual similarities between beans and bullets (bala in Spanish), while the other says that a tortilla-making woman was shot with several bullets, but recovered, and started to make tortillas again, so the workers used to say they are going to the baleada (the shot woman).
    # Regardless of the correct theory, experience one of the most loved and inexpensive street food items in Honduras from the comfort of your own home !''',cost=27)
    # Demo34=Event( ambassador_id=34,title="Tres Leches Cake", description='''Tres Leches Cake
    # (Torta de Tres Leches, Pastel de Tres Leches, Pan Tres Leches, Three-Milk Cake)
    # Tres leches cake is a dense, moist dessert consisting of a sponge cake covered with three types of milk: evaporated, condensed, and whole milk. Although its origins are quite murky, most sources claim it was invented in Nicaragua, but the cake is popular throughout Central America, the United States, and Europe, where it is a staple at numerous celebrations and festivities.
    # It is believed that the original recipe was first printed on milk cans in Latin America, to promote the use of the product, and as a result, the milk companies boosted their milk sales.''',cost=25)


    list = [Demo1,featured, Demo3,Demo4,Demo5,Demo6,Demo7,Demo8,Demo9,Demo10,Demo11,Demo12,Demo13,Demo14,Demo15,Demo16,Demo17,Demo18,Demo19,Demo20,Demo21,Demo22,Demo23,Demo24,Demo25,Demo26,Demo27]
    db.session.add_all(list)
    
    
    db.session.commit()
# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_events():
    db.session.execute('TRUNCATE events CASCADE;')
    db.session.commit()
