"""empty message

Revision ID: c8f9a25881e3
Revises: 5c2ff77609d4
Create Date: 2021-05-10 17:58:09.330521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f9a25881e3'
down_revision = '5c2ff77609d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_calendar', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event_calendar', 'time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_calendar', 'time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event_calendar', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
