"""empty message

Revision ID: a0506bd4b936
Revises: c2798a947848
Create Date: 2021-03-14 15:04:09.013330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0506bd4b936'
down_revision = 'c2798a947848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('region', sa.String(), nullable=False))
    op.drop_column('locations', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('locations', 'region')
    # ### end Alembic commands ###
